version: "3.9"

services:
  backend:
##    build:
##      context: ./backend
##      dockerfile: Dockerfile
    image: mjmacaburas/car-rental-backend:latest
    environment:
      MONGO_URI: mongodb://mongodb:27017/car_rental
      JWT_SECRET: your_jwt_secret
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
##    build:
##      context: ./frontend
##      dockerfile: Dockerfile
    image: mjmacaburas/car-rental-frontend:latest
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
